context:
  version: 24.3.3

package:
  name: mesalib_software
  version: ${{ version }}

requirements:
  build:
    - llvm=15  # 15 to be in line with pyqt: avoid conflict with icu version
    - llvmdev
    - pkg-config
    - meson
    - mako
    - bison
    - cmake
    - pyyaml
    - libxcb
    - xorg-libxrandr
    - xorg-libxshmfence
    - xorg-xproto
    - xorg-libx11
    - xorg-kbproto
    - xorg-libxext
    - xorg-xextproto
    - xorg-glproto
    - xorg-randrproto
    - xorg-renderproto
    - wget
    - tar
    - xz
    - cxx-compiler
  #   - libglvnd-devel
  #   - libdrm
  #   - xorg-libxfixes
  #   - xorg-libxxf86vm
  run:
    - libllvm15
  #   - xorg-libxshmfence


build:
  number: 3
  script: |
    echo PWD: $(pwd)
    echo BUILD: ${BUILD_PREFIX}
    apptainer build --fakeroot ${SRC_DIR}/build.sif $RECIPE_DIR/pixi_apptainer_recipe
    apptainer run -B $PREFIX:/prefix -B ${RECIPE_DIR}:${RECIPE_DIR} -B ${SRC_DIR}:${SRC_DIR} ${SRC_DIR}/build.sif bash -c '. $SRC_DIR/build_env.sh && . $RECIPE_DIR/build_mesa.sh'


