context:
    distro_version: ${{ load_from_file(env.get("PIXI_PROJECT_ROOT") + "/pixi.toml").project.version }} 

package:
    name: morphologist
    version: ${{ distro_version }}

build:
  number: 0
  script: |
    cd "$CASA_BUILD"
    export BRAINVISA_INSTALL_PREFIX="$PREFIX"
    for component in morphologist-nonfree morphologist-gpl morphologist-ui sulci-nonfree morpho-deepsulci; do
      make install-${component}
      make install-${component}-dev
      make install-${component}-usrdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
    done

requirements:
  build:
    - ${{ compiler('cxx') }}
    - libstdcxx-devel_linux-64
    - cmake
    - make

  run:
    - soma ==${{ distro_version }}
    - anatomist ==${{ distro_version }}
    - soma-spm ==${{ distro_version }}
    - capsul ==${{ distro_version }}
    - pytorch
    - torchvision
    # Following dependencies are required to run "morphologist"
    - configobj
    - pyqtwebkit
    - scipy
    - traits
