[project]
name = "neuro-forge"
version = "0.0.3"
description = "Build and publish neuro-forge packages"
channels = ["conda-forge"]
platforms = ["linux-64"]

[activation]
scripts = ["activate.sh"]

[tasks]

[dependencies]
python = "> 2"
conda-build = "*"
rattler-build = "*"
fire = "*"
click = "*"
rich = "*"
git = "*"
gitpython = "*"
pip = "*"
toml = "*"
pyaml = "*"
datalad = "*"
