[project]
name = "neuro-forge"
version = "0.0.4"
description = "Build and publish neuro-forge packages"
channels = ["conda-forge"]
platforms = [ "linux-64", "win-64",]

[activation]
scripts = ["activate.sh"]

[target.win-64.activation]
scripts = ["activate.bat"]

[tasks]

[dependencies]
python = "*"
conda-build = "*"
rattler-build = "*"
fire = "*"
git = "*"
pip = "*"
toml = "*"
pyaml = "*"
