context:
  version: 24.0.3

package:
  name: mesalib-devel-only
  version: ${{ version }}


build:
  number: 0
  script: |
    python "$RECIPE_DIR/download_package.py" mesalib '${{ version }}' "$PREFIX"

requirements:
  build:
    - python
    - requests


about:
  summary: A copy of the mesalib conda-forge package not included in standard paths.
