context:
  version: 24.0.3

package:
  name: mesalib-devel-only
  version: ${{ version }}


build:
  number: 0
  script: |
    mkdir "$PREFIX/mesalib"
    python "$RECIPE_DIR/download_package.py" mesalib '${{ version }}' "$PREFIX/mesalib"

requirements:
  build:
    - python
    - requests
    - conda-package-handling

about:
  summary: A copy of the mesalib conda-forge package not included in standard paths.
