context:
    distro_version: ${{ load_from_file(env.get("PIXI_PROJECT_ROOT") + "/pixi.toml").project.version }} 

package:
    name: soma
    version: ${{ distro_version }}

build:
  number: 0
  script: |
    cd "$CASA_BUILD"
    export BRAINVISA_INSTALL_PREFIX="$PREFIX"
    for component in soma-io aims-free aims-gpl brainvisa-share axon; do
      make install-${component}
      make install-${component}-dev
      make install-${component}-usrdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
    done

requirements:
  build:
    - ${{ compiler('cxx') }}
    - libstdcxx-devel_linux-64
    - cmake
    - make
    - libsigcpp <3
    - libblitz
    - boost-cpp
    - gfortran
    - graphviz
    - dcmtk
    - doxygen
    - pkgconfig
    - numpy
    - pyyaml
    - libminc
    - openjpeg

  run:
    - libblitz
    - boost-cpp
    - dcmtk
    - soma-python ==${{ distro_version }}
    - numpy
    - pyyaml
    - libminc
    - openjpeg
    - pywebp

  #run_constrained:
    #- pygltflib
    #- DracoPy

tests:
  - script: |
      cd "$CASA_BUILD"
      python -m soma_forge test soma
      python -m soma_forge test aims
      python -m soma_forge test axon

    requirements:
      run:
        - cmake
