context:
  version: "0.1.0"

package:
  name: "mlukb"
  version: ${{ version }}


#
#source:
#  path: /tmp/whatsup/dist/whatsup-0.1.0.tar.gz 


build:
  noarch: python

requirements:
#  build:
#    - python
#    - pip

  run: 
    - scikit-learn
    - nilearn
    - r-base

tests:
  - python:
      imports:
        - nilearn
  - script:
    - R --version



about:
  summary: rine project ported to Conda

