context:
  version: "0.0.1"

package:
  name: "mlukb"
  version: ${{ version}}



source:
  path: /tmp/whatsup
  tag: ${{ latest_tag }}


build:
  noarch: python

requirements:
  build:
    - python
    - pip

  run: 
    - colorama

tests:
  - python:
      imports:
        - whatsup


about:
  summary: rine project ported to Conda

