context:
    distro_version: ${{ load_from_file(env.get("PIXI_PROJECT_ROOT") + "/pixi.toml").project.version }} 

package:
    name: populse-db
    version: ${{ distro_version }}

build:
  number: 0
  script: |
    cd "$CASA_BUILD"
    export BRAINVISA_INSTALL_PREFIX="$PREFIX"
    for component in populse-db; do
      make install-${component}
      make install-${component}-dev
      make install-${component}-usrdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
    done

requirements:
  build:
    - make
  
  run:
    - python <=3.10
    - lark-parser >0.7.0
    - python-dateutil

tests:
  - script: "python -m populse_db.test"
    requirements:
      run:
        - pytest
