context:
  version: 4.1.1

package:
  name: gltf-transform
  version: ${{ version }}

source:
  git: https://github.com/donmccurdy/glTF-Transform
  tag:  v${{ version }}

build:
  number: 0
  script: |
    npm install -g @gltf-transform/core @gltf-transform/extensions @gltf-transform/functions @gltf-transform/cli

requirements:
  build:
    - nodejs

  run:
    - nodejs

about:
  homepage: https://gltf-transform.dev
  summary: glTF 2.0 SDK for JavaScript and TypeScript, on Web and Node.js.
  description: |
    glTF Transform supports reading, editing, and writing 3D models in glTF 2.0 format. Unlike 3D modeling tools — which are ideal for artistic changes to geometry, materials, and animation — glTF Transform provides fast, reproducible, and lossless control of the low-level details in a 3D model. The API automatically manages array indices and byte offsets, which would otherwise require careful management when editing files. These traits make it a good choice for bundling, splitting, or optimizing an existing model. It can also be used to apply quick fixes for common issues, to build a model procedurally, or to easily develop custom extensions on top of the glTF format. Because the core SDK is compatible with both Node.js and Web, glTF Transform may be used to develop offline workflows and web applications alike.
