context:
    distro_version: ${{ load_from_file(env.get("PIXI_PROJECT_ROOT") + "/pixi.toml").project.version }} 

package:
    name: soma-python
    version: ${{ distro_version }}

build:
  number: 0
  script: |
    cd "$CASA_BUILD"
    export BRAINVISA_INSTALL_PREFIX="$PREFIX"
    for component in soma-base soma-workflow; do
      make install-${component}
      make install-${component}-dev
      make install-${component}-usrdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
      make install-${component}-devdoc
    done

requirements:
  build:
    - make

  run:
    - python >=3.9
    - populse-db >=3.0
    - pydantic <2
    - pyqt
    - pyqtwebengine
    - numpy
    - ipykernel

tests:
  - script: "python -m soma.tests"
    requirements:
      run:
        - pytest
  - script: "python -m soma_workflow.test"
    requirements:
      run:
        - pytest
