package:
  name: spm12
  version: 7771

source:
  #~ url: https://www.fil.ion.ucl.ac.uk/spm/download/restricted/utopia/spm12/spm12_r${{version}}_Linux_R2019b.zip
  #~ path: /drf/neuro-forge/pool/spm12/spm12_r7771_Linux_R2019b.zip
  path: /tmp/spm12_r7771_Linux_R2019b.zip
  sha256: 227271e160f85f460323105db82e4966532c52b7a8be3f6af0ed452a4b5684d9

requirements:
  run:
    - matlab-runtime-9.7

build:
  number: 0
  script: |
    mkdir "$PREFIX/bin"
    
    cat > "$PREFIX/bin/spm12" <<EOF
    #!/bin/sh
    #
    # https://github.com/spm/spm-docker/blob/main/matlab/singularity.def
    #
    export MCR_INHIBIT_CTF_LOCK=1
    export SPM_HTML_BROWSER=0
    #
    # Start a new interactive shell for SPM12
    #
    exec "\${CONDA_PREFIX}/spm12/run_spm12.sh" "\${CONDA_PREFIX}/MATLAB/MATLAB_Runtime/v97" \${1+"\$@"}
    EOF
    
    chmod +x "$PREFIX/bin/spm12"
    
    mv spm12 "$PREFIX"
    
    "\${PREFIX}/spm12/run_spm12.sh" "\${CONDA_PREFIX}/MATLAB/MATLAB_Runtime/v97" quit
  dynamic_linking:
    binary_relocation: false

about:
  homepage: https://www.fil.ion.ucl.ac.uk/spm/software/spm12/
  license: "GPL-2.0-or-later"
  summary: |
    Analysis of brain imaging data sequences
  description: |
    The SPM software package has been designed for the analysis of brain
    imaging data sequences. The sequences can be a series of images from
    different cohorts, or time-series from the same subject.
    
    A standalone SPM is a version of SPM that has been compiled using
    the MATLAB Compiler so that it does not require the availability
    of a MATLAB licence.
  documentation: https://www.fil.ion.ucl.ac.uk/spm/docs/installation/standalone/

