context:
  name: solar
  version: "8.4.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}


source:
  url: https://www.nitrc.org/frs/download.php/11497/solar-eclipse-8.4.2-static-Linux.zip
  sha256: 11d0becc5b39876a8d9d9e1698289341c69013cbe632000ccfdccca0261400b4

build:
  number: 0

requirements:
  build:
    - unzip


tests:
  - script:
     - solar