context:
    distro_version: ${{ load_from_file(env.get("PIXI_PROJECT_ROOT") + "/pixi.toml").project.version }} 

package:
    name: brainvisa
    version: ${{ distro_version }}

requirements:
  run:
    - brainrat ==${{ distro_version }}
    - disco ==${{ distro_version }}
    - highres-cortex ==${{ distro_version }}
    - morphologist ==${{ distro_version }}
    - primatologist ==${{ distro_version }}
